services:
    vrlab:
        image: wanghsinche/vrlab:c4d85cdcd7e076cb782cd72e1a8e932eba259111
        environment: 
            PORT: 80
            URL: http://0.0.0.0/api
            ID: gzqg
        ports: 
            - "8080:80"
        volumes:  
            - "/home/ubuntu/data:/app/backend/data"
            - "/home/ubuntu/public:/app/backend/public"
        networks:
            - vrlab_network
    
networks:
    vrlab_network:
        # use the bridge driver
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.31.2.0/24
                gateway: 172.31.2.1
                
