# This workflow will build a docker container, publish and deploy it to Tencent TCR when there is a push to the master branch.
#
# To configure this workflow:
##
#

name: Tencent TCR Publish

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  image_url: wanghsinche/vrlab
  docker_username: wanghsince
  docker_password: 062600e4-e4de-4208-9e06-d89bbacc854d

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Login Registry
      run: |
        docker login --username=${docker_username} --password-stdin=${docker_password}

    # Build
    - name: Build Docker image
      run: |        
        docker build . -t ${image_url}:${GITHUB_SHA} 


    # Push the Docker image to TKE Registry
    - name: Publish
      run: |
        docker push ${image_url}:${GITHUB_SHA}


